config/routes.rb
Rails.application.routes.draw do

  root :to => 'accounts#index'

  resources :accounts , only: [:index, :edit, :update, :new, :create]
  resources :users # index new create edit update accounts destroy
  resources :appointments , only: [:edit, :update, :new, :create]
  resources :contacts, only: [:destroy, :edit, :update, :new, :create]

  resources :accounts do
    resources :contacts, only: [:destroy]
  end

  get 'contacts' => 'contacts#index', :as => :contacts_list

  resources :user_sessions # index new create edit update accounts destroy
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CRM</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <header>
    <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menuCollapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">CRM</a>
        </div>
      </div>
      <div class="collapse navbar-collapse" id="menuCollapse">
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li> <%= link_to "Dashboard", accounts_path %></li>
            <li> <%= link_to "Create Account", new_account_path %></li>
            <%
              @accountcounts = Account.where(user: current_user)
              logger.debug 'account count ==== ' +@accountcounts.length.to_s
              if(@accountcounts.length>0)
            %>
              <li> <%= link_to "Create Contact", new_contact_path %></li>
            <% end %>
          <% end %>
        </ul>
        <ul class="nav navbar-nav set-right">
          <% if current_user %>
            <li> <%= link_to "Edit Profile", edit_user_path(current_user.id) %></li>
            <li> <%= link_to "Logout", :logout, method: :post %></li>
          <% else %>
            <li> <%= link_to "Register", new_user_path %></li>
            <li> <%= link_to "Login", :login %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>
  <body>

  <% if flash[:notice]  %>
    <p id="noticea"><%= flash[:notice] %></p>
  <% end  %>

    <section>
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
</html>