config/routes.rb
Rails.application.routes.draw do

  root :to => 'accounts#index'

  resources :accounts , only: [:index, :edit, :update, :new, :create]
  resources :users # index new create edit update accounts destroy
  resources :appointments , only: [:edit, :update, :new, :create]
  resources :contacts, only: [:destroy, :edit, :update, :new, :create]

  resources :accounts do
    resources :contacts, only: [:destroy]
  end

  get 'contacts' => 'contacts#index', :as => :contacts_list

  resources :user_sessions # index new create edit update accounts destroy
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :account_type, :class_name => AccountType, :foreign_key => "account_type_id"
  delegate :name, :to => :account_type, prefix: true, :allow_nil => true

  belongs_to :user

  has_many :contacts, autosave: true
  accepts_nested_attributes_for :contacts, reject_if: :all_blank, allow_destroy: true

  has_many :attendants, through: :contacts

  validates :name, presence: true
  validates :phone, presence: true, format: { with: /\d{3}-\d{3}-\d{4}/}

end

app/models/account_type.rb
class AccountType < ActiveRecord::Base
  has_many :accounts

  #accepts_nested_attributes_for

  # validation if a interface is built
  validates :name, uniqueness: true
  validates :name,  presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  # this is the dashboard
  # returns the current users accounts
  # returns the users current appointments and order by appointment_date and start_time
  # returns the users current contacts which are ordered by account_name, last_name , and first_name
  def index

    @accounts = Account.where(user: current_user).order(name: :asc)
    @appointments = Appointment.where(user: current_user).order(appointment_date: :asc).order(start_time: :asc)
    @contacts = Contact.joins(:account).where(' accounts.user_id=' + current_user.id.to_s).order("accounts.name asc").order(last_name: :asc).order(first_name: :asc)

  end

  # create a instance of the new html package
  # create an instance of an account
  # build/create an instance of atleast one contact
  def new

    @account = Account.new
    @account.contacts.build

  end

  # action to save the account
  def create

    # put the params into a new account object
    @account = Account.new(account_params())

    # set the user data
    @account.user = current_user

    # save
    if @account.save
      # it does save redirect to the account edit
      redirect_to edit_account_path(@account)
    else
      # or go back to the new page
      render  :new
    end

  end

  def edit

      @account = Account.find(params[:id])

      # @account.contacts.find_by!('active = true')

      @account.contacts.build()

      @account.contacts.each { |contact|

        contact.appointments.build

      }

      # binding.pry

  end

  def update

    # logger.debug params[:selected_contacts]
    # logger.debug params[:schedule_appointment]
    if (params[:schedule_appointment])
      redirect_to new_appointment_path(selected_contacts: params[:selected_contacts],account_id: params[:id])
    else
      # get the account
      @account = Account.find(params[:id])
      # logger.debug params[:id]

      # update the account
      if @account.update_attributes(account_params())
        # if it updates
        # return it to the users accounts list
        # redirect_to accounts_path
        # render  :edit
        redirect_to edit_account_path(@account)
      else
        # if it does not update
        # send them back to the edit screen
        render  :edit
      end

    end

  end

  private

  def account_params
    params.require(:account).permit(:account_type_id, :user_id, :name, :phone, :notes, contacts_attributes: [:id, :account_id, :first_name, :last_name, :phone, :notes, :email])
  end



end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for [@account] do |f| %>

  <div class="account set-left">
    <h4>Account</h4>
    <% if @account.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

        <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <% if @account.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>
        <ul>
          <% @account.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :phone %>
      <%= f.telephone_field :phone, placeholder: "Phone" %>
    </div>
    <div class="field">
      <%= f.label :account_type_id %>
      <%= f.collection_select(:account_type_id, AccountType.all, :id, :name) %>
    </div>
    <div class="field">
      <%= f.label :notes %>
      <%= f.text_area :notes %>
    </div>
  </div>

  <div class="contacts set-left">

    <% count=0 %>
    <h4>Contacts</h4>
    <ul class='contact_list' style="list-style: none;">
        <%= f.fields_for :contacts do |contact_fields| %>
        <li>
          <div class="contact">
              <div class="field">
                <% if(@account.contacts[count].id!=nil) %>
                  <%= check_box_tag 'selected_contacts[]', @account.contacts[count].id -%>
                <% end %>
                <%= contact_fields.text_field :first_name , placeholder: "First Name..." %>
                <%= contact_fields.text_field :last_name , placeholder: "Last Name..." %>
              </div>
              <div class="field">
                <%= contact_fields.text_field :phone , placeholder: "Phone Number..." %>
                <%= contact_fields.text_field :email , placeholder: "Email..." %>
                <% if(@account.contacts[count].id!=nil) %>
                  <%= link_to "Delete", [@account, @account.contacts[count]], method: :delete, data: {confirm: "Are you sure you want to delete this ?"} %>
                <% end %>
              </div>
              <div class="field">
                <%= contact_fields.text_area :notes , placeholder: "Notes..." %>
              </div>
          </div>
          <% count=count+1 %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="actions set-bottom">
      <%= f.submit %>
      <%= submit_tag 'Schedule Appointment', name: 'schedule_appointment' %>
  </div>


<% end %>

app/views/accounts/edit.html.erb
<h4>Edit</h4>

<%= render 'form' %>

app/views/accounts/index.html.erb
<div class="index">

      <div class="col-md-4">
        <h4>Accounts</h4>
        <% @accounts.each do |account| %>
            <p><%= link_to account.name + ' ' + account.phone , edit_account_path(account) , class: "link-bold" %> </p>
        <% end %>
      </div>

      <div class="col-md-4">

        <h4>Appointments</h4>
        <ul>
          <% @appointments.each do |appointment| %>

            <li class="li-reduce-indent"><%= link_to appointment.appointment_type_name + ' ' + appointment.appointment_date.strftime("%e-%B-%Y").to_s + ' ' + Appointment.times[appointment.start_time]  , edit_appointment_path(appointment) , class: "link-bold" %>
            <h5>With...</h5>
              <% appointment.attendants.each do |attendant| %>
                <% if((attendant.contact!=nil))%>
                  <p>
                     <%= attendant.contact_first_name %>
                     <%= attendant.contact_last_name %>
                     <%= attendant.contact_phone %>
                     <%= attendant.contact.account.name %>
                  </p>
                <% end %>
              <% end %>
            </li>
            <!-- </br> -->
          <% end %>

        </ul>

      </div>

    <div class="col-md-4">
      <%= form_tag "/appointments/new", method: "get" do %>
        <h4>Contacts</h4>
        <% @contacts.each do |contact| %>
          <%= check_box_tag 'selected_contacts[]', contact.id -%>
          <%= link_to contact.first_name + ' ' + contact.last_name + ', ' + contact.account.name   , edit_contact_path(contact)  %></br>
        <% end %>
        <%= submit_tag 'Schedule Appointment', name: 'schedule_appointment' %>
      <% end %>
    <div>

  </div>

app/views/accounts/new.html.erb
<h4>New</h4>

<%= render 'form' %>